### ISSUE TITLE
base64 decode fail.

### ISSUE THREAD

**Issue by tobecats** [JinnLynn/genpac#10]
while i try to run genpac,  the wrong messages is "base64 decode fail."
maybe the problem happned in core.py where try to decode the content, but i don't know how to solve it.

**Comment by JinnLynn** [comment]
gfwlist maybe downloads fail.

**Comment by renkun-ken** [comment]
I run `wget https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt` and download the file to local and it also says `base64 decode fail.`.

**Comment by passos** [comment]
same problem.

ubuntu 17.10
genpac 1.4.1

run following command

`$ genpac --proxy="SOCKS5 127.0.0.1:1080" --gfwlist-proxy="SOCKS5 127.0.0.1:1080" -o autoproxy.pac --gfwlist-url="https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt"
base64 decode fail.`

I can download gfwlist manually.

**Comment by Cliff2016** [comment]
base64 decode fail， ubuntu 17.04,  genpac 1.4.1

**Comment by liuny05** [comment]
Same problem.
Ubuntu 16.04
genpac 1.4.1
python2.7.12
```
$ genpac -p "SOCKS5 127.0.0.1:1080"
base64 decode fail.
```
Download `gfwlist.txt` manually but get the same result.
```
$ genpac -p "SOCKS5 127.0.0.1:1080" --gfwlist-local=gfwlist.txt
base64 decode fail.
```

**Comment by liuny05** [comment]
Change genpac to latest development version by running
`pip install https://github.com/JinnLynn/genpac/archive/master.zip` 
solved my problem.
