### ISSUE TITLE
ubuntu 16.04 LTS 报错 怎么破

### ISSUE THREAD

**Issue by q54528** [JinnLynn/genpac#11]
dd@ubuntu:~$        --gfwlist-url="https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt" 

bash: --gfwlist-url=https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt: 没有那个文件或目录

dd@ubuntu:~$        --output="~/autoproxy.pac"

bash: --output=~/autoproxy.pac: 没有那个文件或目录

**Comment by JinnLynn** [comment]
请先了解如何正确使用终端命令。

**Comment by q54528** [comment]
正确使用后提示 64位解码报错，如何处理？我是linux小白，谢谢
