### ISSUE TITLE
为何一直报参数错误？

### ISSUE THREAD

**Issue by tqknight1984** [JinnLynn/genpac#19]
[root@VM_31_126_centos ~]# genpac -v
genpac 1.4.1
[root@VM_31_126_centos ~]# genpac --pac-proxy="SOCKS5 127.0.0.1:1080" --gfwlist-local=~/gfwlist.txt
usage: genpac [-p PROXY] [--gfwlist-url GFWLIST_URL]
              [--gfwlist-proxy GFWLIST_PROXY] [--gfwlist-local GFWLIST_LOCAL]
              [--update-gfwlist-local] [--gfwlist-disabled]
              [--user-rule USER_RULE] [--user-rule-from USER_RULE_FROM] [-P]
              [-o OUTPUT] [-c CONFIG_FROM] [-z] [--init [INIT]] [-v] [-h]
genpac: error: unrecognized arguments: --pac-proxy=SOCKS5 127.0.0.1:1080
[root@VM_31_126_centos ~]# genpac --format=pac --pac-proxy="SOCKS5 127.0.0.1:1080" 
usage: genpac [-p PROXY] [--gfwlist-url GFWLIST_URL]
              [--gfwlist-proxy GFWLIST_PROXY] [--gfwlist-local GFWLIST_LOCAL]
              [--update-gfwlist-local] [--gfwlist-disabled]
              [--user-rule USER_RULE] [--user-rule-from USER_RULE_FROM] [-P]
              [-o OUTPUT] [-c CONFIG_FROM] [-z] [--init [INIT]] [-v] [-h]
genpac: error: unrecognized arguments: --format=pac --pac-proxy=SOCKS5 127.0.0.1:1080
[root@VM_31_126_centos ~]# genpac --format=pac --pac-proxy="SOCKS5 127.0.0.1:1080"  --gfwlist-local=~/gfwlist.txt
usage: genpac [-p PROXY] [--gfwlist-url GFWLIST_URL]
              [--gfwlist-proxy GFWLIST_PROXY] [--gfwlist-local GFWLIST_LOCAL]
              [--update-gfwlist-local] [--gfwlist-disabled]
              [--user-rule USER_RULE] [--user-rule-from USER_RULE_FROM] [-P]
              [-o OUTPUT] [-c CONFIG_FROM] [-z] [--init [INIT]] [-v] [-h]
genpac: error: unrecognized arguments: --format=pac --pac-proxy=SOCKS5 127.0.0.1:1080
[root@VM_31_126_centos ~]#

**Comment by JinnLynn** [comment]
通过pip安装的版本是1.4.1，github上的版本是2.0b2，有些参数改了，你可以使用pip install https://github.com/JinnLynn/genpac/archive/master.zip安装开发版本

**Comment by tqknight1984** [comment]
多谢，已解决！
