### ISSUE TITLE
fetch gfwlist fail.

### ISSUE THREAD

**Issue by ray007great** [JinnLynn/genpac#3]
fetch gfwlist fail.
什么鬼。
墙里墙外都fail

**Comment by FireZ-ZLF** [comment]
--gfwlist-url="https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt"

**Comment by gengmu** [comment]
gfwlist.txt 已经下载了！
genpac启动时还是：fetch gfwlist fail

**Comment by wd** [comment]
需要指定下配置文件应该是。
genpac init 新建好配置文件，配置好。然后执行 genpac -c config.ini

**Comment by JinnLynn** [comment]
如果你无法直接访问gfwlist，请检查获取gfwlist时的代理参数--gfwlist-proxy。

**Comment by xxxifan** [comment]
2楼解决了我的问题，感谢

**Comment by dajyaretakuya** [comment]
2楼works~
