### ISSUE TITLE
Ubuntu chrome 突然不能使用自动代理文件pac了,  Firefox没问题

### ISSUE THREAD

**Issue by chn-yang** [JinnLynn/genpac#31]

**Comment by xiayurain95** [comment]
same issue after upgrade chrome to the newest version

**Comment by chn-yang** [comment]
> 
> 
> same issue after upgrade chrome to the newest version

OK

**Comment by 724399396** [comment]
I have same issue, have any idea to fix it @chn-yang  @xiayurain95

**Comment by xiayurain95** [comment]
> I have same issue, have any idea to fix it @chn-yang @xiayurain95

  Chrome seems turn off all net-externals flags.
We can use this command to record network event of chrome since it's startup.
   `google-chrome-stable --proxy-pac-url=[your-pac-file] --log-net-log=[log-location]`
We can use [https://netlog-viewer.appspot.com/](https://netlog-viewer.appspot.com/) to view our logs.
In my case, once row named **PAC_FILE_DECIDER** and the detail of this event is 
`t=466 [st=0] +PAC_FILE_DECIDER  [dt=0]`
`t=466 [st=0]   +PAC_FILE_DECIDER_FETCH_PAC_SCRIPT  [dt=0]`
`                --> source = "Custom PAC URL: file:///home/xiayu/code/dac/autoproxy.pac"`
`t=466 [st=0]   -PAC_FILE_DECIDER_FETCH_PAC_SCRIPT`
`               --> net_error = -301 (ERR_DISALLOWED_URL_SCHEME)`
`t=466 [st=0] -PAC_FILE_DECIDER`
I searched the **ERR_DISALLOWED_URL_SCHEME**, some page says it means The scheme of the URL is disallowed.
Well, it's  confused, I decide use whole system proxy or just downgrade the chrome :(

**Comment by chn-yang** [comment]
> > I have same issue, have any idea to fix it @chn-yang @xiayurain95
> 
> Chrome seems turn off all net-externals flags.
> We can use this command to record network event of chrome since it's startup.
> `google-chrome-stable --proxy-pac-url=[your-pac-file] --log-net-log=[log-location]`
> We can use https://netlog-viewer.appspot.com/ to view our logs.
> In my case, one row named **PAC_FILE_DECIDER** and the detail of this event is
> `t=466 [st=0] +PAC_FILE_DECIDER [dt=0]`
> `t=466 [st=0] +PAC_FILE_DECIDER_FETCH_PAC_SCRIPT [dt=0]`
> ` --> source = "Custom PAC URL:[my-pac-file-path]"`
> `t=466 [st=0] -PAC_FILE_DECIDER_FETCH_PAC_SCRIPT`
> ` --> net_error = -301 (ERR_DISALLOWED_URL_SCHEME)`
> `t=466 [st=0] -PAC_FILE_DECIDER`
> I searched the **ERR_DISALLOWED_URL_SCHEME**, some page says it means The scheme of the URL is disallowed.
> Well, it's confused, I decide use whole system proxy or just downgrade the chrome :(

Regret， I want use firefox replace chrome on many things

**Comment by 724399396** [comment]
> > I have same issue, have any idea to fix it @chn-yang @xiayurain95
> 
> Chrome seems turn off all net-externals flags.
> We can use this command to record network event of chrome since it's startup.
> `google-chrome-stable --proxy-pac-url=[your-pac-file] --log-net-log=[log-location]`
> We can use https://netlog-viewer.appspot.com/ to view our logs.
> In my case, one row named **PAC_FILE_DECIDER** and the detail of this event is
> `t=466 [st=0] +PAC_FILE_DECIDER [dt=0]`
> `t=466 [st=0] +PAC_FILE_DECIDER_FETCH_PAC_SCRIPT [dt=0]`
> ` --> source = "Custom PAC URL:[my-pac-file-path]"`
> `t=466 [st=0] -PAC_FILE_DECIDER_FETCH_PAC_SCRIPT`
> ` --> net_error = -301 (ERR_DISALLOWED_URL_SCHEME)`
> `t=466 [st=0] -PAC_FILE_DECIDER`
> I searched the **ERR_DISALLOWED_URL_SCHEME**, some page says it means The scheme of the URL is disallowed.
> Well, it's confused, I decide use whole system proxy or just downgrade the chrome :(

plugin SwitchyOmega work perfect

**Comment by xiayurain95** [comment]
Wow, it works, thanks!@724399396

**Comment by pipchu** [comment]
> same issue after upgrade chrome to the newest version

The same problem occurred on my __Ubuntu 16.04.2 LTS x64__ with chrome version  __72.0.3626.109 (Official Build) (64-bit)__.
I simply deleted the configuration file directory located in __$HOME/.config/google-chrome__.
It works again!!!

**Comment by chn-yang** [comment]
> Wow, it works, thanks!@724399396



> > > I have same issue, have any idea to fix it @chn-yang @xiayurain95
> > 
> > 
> > Chrome seems turn off all net-externals flags.
> > We can use this command to record network event of chrome since it's startup.
> > `google-chrome-stable --proxy-pac-url=[your-pac-file] --log-net-log=[log-location]`
> > We can use https://netlog-viewer.appspot.com/ to view our logs.
> > In my case, one row named **PAC_FILE_DECIDER** and the detail of this event is
> > `t=466 [st=0] +PAC_FILE_DECIDER [dt=0]`
> > `t=466 [st=0] +PAC_FILE_DECIDER_FETCH_PAC_SCRIPT [dt=0]`
> > ` --> source = "Custom PAC URL:[my-pac-file-path]"`
> > `t=466 [st=0] -PAC_FILE_DECIDER_FETCH_PAC_SCRIPT`
> > ` --> net_error = -301 (ERR_DISALLOWED_URL_SCHEME)`
> > `t=466 [st=0] -PAC_FILE_DECIDER`
> > I searched the **ERR_DISALLOWED_URL_SCHEME**, some page says it means The scheme of the URL is disallowed.
> > Well, it's confused, I decide use whole system proxy or just downgrade the chrome :(
> 
> plugin SwitchyOmega work perfect https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif?hl=en

work too, thanks!

**Comment by leaf-lxh** [comment]
It seems like the Chrome disallows proxy rules reading using file:// protocol. (includes SwitchOmega v2.5.20 extention)  

I installed the apache2, copied the pac file to /var/www/html/, and changed my configuration URL from file://pac_path to http://127.0.0.1/pac_file.   

Everything backs to normal.  

But be aware that by default the apache2 will expose your 80 port to 0.0.0.0.  
You may need do some configuration in /etc/apache2/ports.conf and maybe other files to avoid security risk.

**Comment by uncoseason** [comment]
chrome://flags/#network-service -> Disabled
it works.

**Comment by chn-yang** [comment]
> chrome://flags/#network-service -> Disabled
> it works.

Work perfect, Thanks!

**Comment by chn-yang** [comment]
> chrome://flags/#network-service -> Disabled
> it works.

Chrome version 76.0.3809.87 , don't work .. sad
everyone have any other way?

**Comment by F-Que** [comment]
> > chrome://flags/#network-service -> Disabled
> > it works.
> 
> Chrome version 76.0.3809.87 , don't work .. sad
> everyone have any other way?

It seems that Chrome will no longer support "file://" pac url.
Launching with flag "--disable-features=NetworkService" seems work on version 76, but not in version 77.
Setting up an http file server locally and change the url into an "http://" one  may be an available way recently.

**Comment by F-Que** [comment]
> > chrome://flags/#network-service -> Disabled
> > it works.
> 
> Chrome version 76.0.3809.87 , don't work .. sad
> everyone have any other way?

It seems that Chrome will no longer support "file://" pac url.
Launching with flag "--disable-features=NetworkService" seems work on version 76, but not in version 77.
Setting up an http file server locally and change the url into an "http://" one  may be an available way recently.

**Comment by ygcaicn** [comment]
maybe you need this.
https://github.com/ygcaicn/autopac-heroku
