### ISSUE TITLE
最近 genpac 生成的 pac 无法正常工作

### ISSUE THREAD

**Issue by zyf0330** [JinnLynn/genpac#36]
Ubuntu 19.10
Chrome 79

pac 由 gfwlist 生成，chrome 使用 SwitchyOmega，不论是 ubuntu 系统代理使用 pac 或 SwitchyOmega使用 pac 的方式，国内网站均会走到 PROXY
改用 https://github.com/breakwa11/GFWList2PAC 生成的 pac 正常工作

**Comment by freeAhao** [comment]
ios 自动代理使用该项目生成的pac无法使用
