### ISSUE TITLE
能否做到不同的规则使用不同的代理

### ISSUE THREAD

**Issue by hitechbeijing** [JinnLynn/genpac#4]
出于一些特殊情况的考虑，需要不同的地址使用不同的代理，但目前genpac似乎无法做到。请问可否考虑增加此功能？谢谢。

**Comment by JinnLynn** [comment]
目前还没有增加该功能的打算，不好意思

**Comment by hitechbeijing** [comment]
@JinnLynn 十分感谢告知。

**Comment by yulanggong** [comment]
我也想问这个问题。对于常开 fiddler 之类调试工具的人来说，这个功能还是很有用的，调试域名走调试工具，gfwlist 走境外代理，其他域名直联。
