### ISSUE TITLE
执行 genpac -p PROXY 报错 fetch gfwlist fail

### ISSUE THREAD

**Issue by lkqin** [JinnLynn/genpac#5]
执行 genpac -p PROXY  , genpac --gfwlist-url=URL 
报错 fetch gfwlist fail

**Comment by JinnLynn** [comment]
检查是否能直接访问gfwlist，如果不行，使用代理

**Comment by JinnLynn** [comment]
对不起，你所说的错误不是代理问题，确实是BUG，当没有配置文件也没有--gfwlist-url参数时会出现。

相关issue: #3
