### ISSUE TITLE
默认模式跳过/开头

### ISSUE THREAD

**Issue by fpfeng** [JinnLynn/genpac#7]
意思是不处理/^开头吧？实际就blogspot和google大概几十条国别域名，再加一条naver.jp。既然已经特例跳过/开头，为什么不特例处理它们呢，不太明白，好像有点不合理？
最后必须谢谢你的程序。

**Comment by JinnLynn** [comment]
已支持以`/`开始的规则，Google的国别域名可使用，但blogspot依旧无法识别，因为它在gfwlist中的规则没有顶级域名信息，建议在自定义规则中添加。
